<?php

namespace ContainerWebmSz2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Dm9lZj0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Dm9lZj0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Dm9lZj0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'car' => ['privates', '.errored..service_locator.Dm9lZj0.App\\Entity\\Car', NULL, 'Cannot autowire service ".service_locator.Dm9lZj0": it needs an instance of "App\\Entity\\Car" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'car' => 'App\\Entity\\Car',
            'entityManager' => '?',
            'slugger' => '?',
        ]);
    }
}
