<?php

namespace ContainerWebmSz2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PeY9mp_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.peY9mp.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.peY9mp.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'companyRepository' => ['privates', 'App\\Repository\\CompanyRepository', 'getCompanyRepositoryService', true],
            'openingRepository' => ['privates', 'App\\Repository\\OpeningRepository', 'getOpeningRepositoryService', true],
        ], [
            'companyRepository' => 'App\\Repository\\CompanyRepository',
            'openingRepository' => 'App\\Repository\\OpeningRepository',
        ]);
    }
}
