<?php

namespace ContainerWebmSz2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOpeningService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator..xog4oS.App\Entity\Opening' shared service.
     *
     * @return \App\Entity\Opening
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator..xog4oS": it needs an instance of "App\\Entity\\Opening" but this type has been excluded in "config/services.yaml".');
    }
}
