<?php

namespace ContainerQYvaKc3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5vfTQdEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5vfTQdE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5vfTQdE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'openingRepository' => ['privates', 'App\\Repository\\OpeningRepository', 'getOpeningRepositoryService', true],
        ], [
            'openingRepository' => 'App\\Repository\\OpeningRepository',
        ]);
    }
}
