<?php

namespace ContainerQYvaKc3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Q4JCdfrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.q4JCdfr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.q4JCdfr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'opening' => ['privates', '.errored..service_locator.q4JCdfr.App\\Entity\\Opening', NULL, 'Cannot autowire service ".service_locator.q4JCdfr": it needs an instance of "App\\Entity\\Opening" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'opening' => 'App\\Entity\\Opening',
        ]);
    }
}
