<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFoBLJnQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFoBLJnQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFoBLJnQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFoBLJnQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFoBLJnQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'FoBLJnQ',
    'container.build_id' => '09a71f2b',
    'container.build_time' => 1709632468,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFoBLJnQ');
